### PR TITLE
release: v0.2.0

### PR DESCRIPTION
**Pull request by desimone**
**Before tagging**

- [x] Review and update examples 
- [x] Review and update dockerfiles
- [x] Review and update docs
- [x] Review and update changelog
- [x] Review and update upgrading guide

**After tagging**
- [ ] Update github release docs
- [ ] Publish tagged version of documentation
- [ ] Review and update helm-charts (merge after tag)

### CODE REVIEW

**Comment by travisgroth** [comment]
We should have #241  and #250 in for this release.

I'll link in a helm chart update when ready.

**Comment by desimone** [comment]
\cc @victornoel about to cut `v0.2.0` if you wanted to kick the tires with latest

**Comment by victornoel** [comment]
Ah sorry this time I can't, I'm in vacation mode ;) thanks for the heads-up
anyway!

Le sam. 3 août 2019 à 21:29, Bobby DeSimone <notifications@github.com> a
écrit :

**Comment by desimone** [comment]
Enjoy!

**Pull request merged**
