### PR TITLE
Docs: Convert Console Config to Table

### PR DESCRIPTION
**Pull request by alexfornuto**
## Summary

- Updates the Pomerium Console config values page with the latest updates from console.
- Converts the page to table format.

## Related issues

https://github.com/pomerium/pomerium-console/pull/2390

## Checklist

- [x] reference any related issues
- [x] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

**Comment by alexfornuto** [comment]
Hold for console 17.

**Comment by travisgroth** [comment]
@alexfornuto as discussed yesterday, table format is good if we can insert anchors for inbound linking purposes.

**Comment by alexfornuto** [comment]
> @alexfornuto as discussed yesterday, table format is good if we can insert anchors for inbound linking purposes.

Completed in https://github.com/pomerium/pomerium/pull/3109/commits/ab91534320aae4242f219c7af8dfbf632f602e25

**Comment by alexfornuto** [comment]
Will merge with the release of Console 0.17.

**Pull request merged**
