### PR TITLE
Remove unnecessary viper.New()

### PR DESCRIPTION
**Pull request by yegle**
NewDefaultOptions() already set the viper field to a non-nil value.
Trivial change.

### CODE REVIEW

**Comment by travisgroth** [comment]
Looks like you started from a stale branch.  Can you update to fix the conflicts?  Otherwise LGTM.

**Comment by travisgroth** [comment]
Upon further investigation, I think this pattern is silly looking but necessary with the current structure.  https://github.com/pomerium/pomerium/pull/850#discussion_r437825194

**Comment by yegle** [comment]
How about now?

**Comment by travisgroth** [comment]
I was thinking that might work.  It does look like it should be okay.

**Pull request merged**
