### PR TITLE
proxy: Do not override upstream security headers

### PR DESCRIPTION
**Pull request by chemhack**
**Checklist**:
- [ ] updated docs
- [ ] unit tests added
- [ ] related issues referenced
- [ ] ready for review

### CODE REVIEW

**Comment by desimone** [comment]
Hi @chemhack are you still working on this? Anything I can do to help?

**Comment by chemhack** [comment]
hi @desimone, sorry i didn't have time test this yet. would you have time to take over this?

**Comment by desimone** [comment]
@chemhack sure -- can you help be better understand the use case. As of now, the security headers are pretty conservative. Are you experiencing an issue with a downstream app because of them?

**Comment by chemhack** [comment]
@desimone we have some pages which suppose to live in an iframe. it should be possible to override these settings from upstream.

**Comment by desimone** [comment]
@chemhack I see what you are saying. I think it makes sense to add this as a policy specific setting.  

What do you think about something along the lines of...

```yaml
- from: iframe.corp.example.com 
  to: http://iframe
  allowed_domains:
      - example.com
  respect_upstream_headers: true
```

**Comment by chemhack** [comment]
> @chemhack I see what you are saying. I think it makes sense to add this as a policy specific setting.
> 
> What do you think about something along the lines of...
> 
> ```yaml
> - from: iframe.corp.example.com 
>   to: http://iframe
>   allowed_domains:
>       - example.com
>   respect_upstream_headers: true
> ```

this is even better setup, closing this one.

**Pull request closed without merging**
