### PR TITLE
deployment: add arm64v8 dockerfile

### LINKED ISSUE #125: Add docker image for arm64v8 architecture
Hi,
Great project

It would be great if a docker image for arm64 could be added as more and more SBC are using this architecture.
I was able to build the docker image by using the existing `Dockerfile.arm32v7` file and changing
```
ENV GOARCH=arm
ENV GOARM=7
```
to
```
ENV GOARCH=arm64
```

### PR DESCRIPTION
**Pull request by deltabweb**
Please let me know if any modification is needed, happy to help with that

Closes #125

### CODE REVIEW

**Comment by desimone** [comment]
@deltabweb thank you! 

I've configured things on the dockerhub end so latest should be getting auto-build as will subsequent tagged releases. Let me know if it works on your end.

**Comment by deltabweb** [comment]
Hmm, doesn't seem to work with the latest tag:
image

I had a quick look on Docker hub and it says arm6486-latest, I guess there's a tag / name problem somewhere as it should probably say arm64v8-latest instead
image

**Comment by desimone** [comment]
Sorry about that, very much a typo. Updated build coming. 
Screen Shot 2019-05-22 at 9 43 23 PM

**Comment by deltabweb** [comment]
No worries, trial and error is fine :)
It seems that there is still something that isn't configured properly:
image

**Comment by desimone** [comment]
I'm not sure why it is failing (what does no suitable node mean?). 

Dockerhub looks properly configured to me. What operating system are you running?

I can't test this because I don't have this version of arm but the image looks like it missing an envar?

Screen Shot 2019-05-23 at 4 08 46 PM

https://cloud.docker.com/u/pomerium/repository/registry-1.docker.io/pomerium/pomerium/builds/457c8fe2-71b7-417a-b472-b70fff8e164e

**Comment by deltabweb** [comment]
This screenshot is from Portainer, it means that the architecture of the image doesn't match my device's architecture. It is running Debian.

I think the architecture might have to be set to arm64v8 somewhere but I am not familiar with dockerhub. To use my custom image with Portainer, I had to create a docker manifest that declares that this image is for arm64v8 architecture. Maybe you can set that up somewhere?

Thanks for this great project and the support BTW

**Pull request merged**
