### PR TITLE
deployment: expose config file interface in docker images

### PR DESCRIPTION
**Pull request by travisgroth**
Part of #115

- Existing env-only users should be unaffected.  
- Adds a default yaml location for users to mount a config over 
- Moves the config option to CMD so that pomerium args can be specified at runtime when desired 
  - Example use case is if someone wanted to pass their config as toml or json for some reason
  ```shell
  08:23 $ docker run -it pomerium -help
  Usage of /bin/pomerium:
    -config string
    	  Specify configuration file location
    -version
    	  prints the version
  ```

- I slurped in a test coverage fix that took my last PR down 0.1% and was annoying me 😄 

**Checklist**:
- [x] updated docs
- [x] unit tests added
- [x] related issues referenced
- [x] ready for review

### CODE REVIEW

**Comment by travisgroth** [comment]
Hah yep shame is a powerful tool

**Comment by desimone** [comment]
If you don't mind squashing, this is good to merge. 👍

**Comment by travisgroth** [comment]
Squashed to two (seems like they should be separate).  Let me know if you really want it down to one.

**Comment by desimone** [comment]
Two makes sense here. 👍

**Pull request merged**
