### PR TITLE
config: fix set_response_headers

### PR DESCRIPTION
**Pull request by calebdoxsey**
## Summary
Fix the set response headers option so that its set with the correct precedence and `disable: 1` works for the route-specific option.

## Related issues
- https://github.com/pomerium/pomerium/issues/4013

 

## Checklist
- [x] reference any related issues
- [x] updated unit tests
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

**Comment by calebdoxsey** [comment]
Per the docs:

> Specifies a set of headers that will be added to responses to requests matching this route. Headers specified at this level are applied before headers from the enclosing :ref:`envoy_v3_api_msg_config.route.v3.VirtualHost` and :ref:`envoy_v3_api_msg_config.route.v3.RouteConfiguration`.

So we can't use the virtual host `ResponseHeadersToAdd` option since we want the route-specific ones to be applied last.

**Review by wasaga — COMMENTED** [review]
Is it expected that the following config results in no headers set in the response? 

```yaml
set_response_headers:
  "disable": "true"

routes:
  - from: https://httpbin.localhost.pomerium.io
    to: https://httpbin.org
    pass_identity_headers: true
    allowed_domains: ["gmail.com"]
    set_response_headers:
      "my-custom-header": "hello there"
```

**Comment by calebdoxsey** [comment]
I don't know how it should behave.

**Comment by desimone** [comment]
I want to find out why this functionality was added before making a decision.

**Comment by calebdoxsey** [comment]
I don't know why this functionality was added.

**Review by desimone — APPROVED** [review]

**Review by wasaga — APPROVED** [review]

**Pull request merged**
