### PR TITLE
directory service

### PR DESCRIPTION
**Pull request by calebdoxsey**
## Summary
This moves group-related functionality from our current identity providers into a directory provider and uses service accounts to query the information. Synchronization of the data was added to the identity manager.

## Related issues
For #865 

**Checklist**:
- [x] add related issues
- [ ] updated docs
- [x] updated unit tests
- [ ] updated UPGRADING.md
- [ ] ready for review

### CODE REVIEW

**Comment by calebdoxsey** [comment]
@desimone I still need to update the docs, but I wanted to get your feedback in case we want to rename anything before I update them.

**Comment by desimone** [comment]
@calebdoxsey on it.

**Comment by calebdoxsey** [comment]
I will create another PR for the documentation changes.

**Comment by sly-net** [comment]
Thank you for this contribution @calebdoxsey.

I'm currently using [Dex](https://github.com/dexidp/dex/) as IdP provider with Pomerium 0.9.4. _allowed_groups_ works perfectly (I had to set "openid,profile,email,**groups**,offline_access" for _idp_scopes_ in Pomerium's configuration).
With those new changes, is there any easy/realistic solution to keep using _allowed_groups_ (which is a quite simple, good and common way to perform authorization) when using a "custom" OIDC IdP like Dex, Keycloack, etc. ?

**Comment by calebdoxsey** [comment]
@sly-net AFAIK there is not currently a solution for groups for custom OIDC providers like Dex, Keycloak, etc.

**Comment by sly-net** [comment]
Thank you all for the information :wink:

**Pull request merged**
