### PR TITLE
authorize: remove DataBrokerData input

### PR DESCRIPTION
**Pull request by calebdoxsey**
## Summary
Currently we use session, user and group data from the `input` in the rego policy. This data is also available in `data.databroker_data`, so this PR updates the policy to only look at data, and stops passing in the session, user and group data.

## Checklist
- [ ] reference any related issues
- [ ] updated docs
- [x] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

**Review by wasaga — APPROVED** [review]
I only have basic understanding of how rego policies work, thus would appreciate a second pair of eyes @pomerium/dev-backend

**Review by desimone — CHANGES_REQUESTED** [review]
The code LGTM but a simple policy is failing for me.

```yaml
policy:
  - from: https://verify.localhost.pomerium.io
    to: https://verify.pomerium.com/
    allowed_users:
      - bdd@pomerium.com
    pass_identity_headers: true
```

```json
{
  "level": "info",
  "service": "authorize",
  "request-id": "766960ae-0f8c-4113-979a-ef6f4a27229b",
  "check-request-id": "5a145e27-7dfa-45eb-b383-ae49d9fecca2",
  "method": "GET",
  "path": "/",
  "host": "verify.localhost.pomerium.io",
  "query": "",
  "allow": false,
  "status": 403,
  "message": "authorize check",
  "user": "bdd@pomerium.com",
  "groups": [],
  "time": "2021-02-02T11:15:13-08:00"
}
{
  "level": "error",
  "service": "envoy",
  "name": "lua",
  "time": "2021-02-02T11:15:13-08:00",
  "message": "script log: [string \\\"function envoy_on_request(request_handle)...\\\"]:16: attempt to index a nil value"
}
{
  "level": "info",
  "service": "envoy",
  "upstream-cluster": "",
  "method": "GET",
  "authority": "verify.localhost.pomerium.io",
  "path": "/",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36",
  "referer": "",
  "forwarded-for": "192.168.1.63",
  "request-id": "5a145e27-7dfa-45eb-b383-ae49d9fecca2",
  "duration": 13.193625,
  "size": 11565,
  "response-code": 403,
  "response-code-details": "ext_authz_denied",
  "time": "2021-02-02T11:15:13-08:00",
  "message": "http-request"
```

Screen Shot 2021-02-02 at 11 16 07 AM
Screen Shot 2021-02-02 at 11 15 59 AM

**Comment by calebdoxsey** [comment]
I don't know why it doesn't work. I spent many hours trying to port the logic to rego without much luck. I'll try again.

**Comment by calebdoxsey** [comment]
Looks like the issue is the `/` in the user ids. This gets transformed into a more deeply nested object. eg:

```json
{
  "type.googleapis.com": {
    "user.User": {
      "google": {
         "ID": {}
       } 
    }
  }
}
```

**Review by desimone — APPROVED** [review]
LGTM;

**Pull request merged**
