### PR TITLE
core/ci: store ui bundles in lfs

### PR DESCRIPTION
**Pull request by calebdoxsey**
## Summary
Store `index.js` and `index.css` using LFS.

## Related issues
For https://github.com/pomerium/internal/issues/1788
 

## Checklist

- [x] reference any related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

**Comment by wasaga** [comment]
do we need rebuild index.css/js ? 

```
➜  pomerium-3 git:(cdoxsey/lfs) make build 
==> yarn
cd ui ; yarn install --network-timeout 120000
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.12s.
==> build-ui
yarn run v1.22.19
$ ts-node ./scripts/esbuild.ts

  dist/index.js     3.7mb ⚠️
  dist/index.css  125.4kb

✨  Done in 1.61s.
==> get-envoy
==> deps-build
==> deps-release
==> build-deps
==> build-go
==> build
➜  pomerium-3 git:(cdoxsey/lfs) ✗ git status
On branch cdoxsey/lfs
Your branch is up to date with 'origin/cdoxsey/lfs'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ui/dist/index.css
        modified:   ui/dist/index.js
```

**Comment by calebdoxsey** [comment]
I did. Maybe it's not deterministic. In which case the pre-commit hook I added isn't going to work.

**Comment by calebdoxsey** [comment]
Pulled it down on mac and re-ran the build... it gave me the same files. I guess we can't rely on this build process. We will each end up committing a different build.

**Comment by calebdoxsey** [comment]
Not doing this for now.

**Pull request closed without merging**
