### PR TITLE
internal/controlplane: enable envoy use remote address

### LINKED ISSUE #1013: proxy: x-forwarded-for not set
## What happened?

`x-forwarded-for` headers are not being set by default.

## What did you expect to happen?

`x-forwarded-for` headers are being set by default.

## How'd it happen?

```
policy:
  - from: https://httpbin.imac.bdd.io
    to: http://httpbin.org
```

Go to https://httpbin.imac.bdd.io/headers

```json

{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en-US,en;q=0.9", 
    "Cache-Control": "max-age=0", 
    "Content-Length": "0", 
    "Cookie": "", 
    "Dnt": "1", 
    "Host": "httpbin.imac.bdd.io", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "cross-site", 
    "Sec-Fetch-User": "?1", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "30000"
  }
}
```

I expect x-forarded-for headers above.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): `v0.9.0+ecdf7ee`
- Server Operating System/Architecture/Cloud: OSX

## Additional context

- https://github.com/pomerium/pomerium/issues/1012

### PR DESCRIPTION
**Pull request by cuonglm**
## Related issues
Fixes #1013

**Checklist**:
- [x] add related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [x] ready for review

### CODE REVIEW

**Comment by cuonglm** [comment]
@desimone I don't see anyway to make envoy forward `X-Forwarded-For` to upstream services. See related discussion in https://github.com/istio/istio/issues/7607.

So I think the correct behavior here is relying on `X-Envoy-External-Address`, and the upstream services should explicitly check for that instead of `X-Forwarded-For`.

**Comment by travisgroth** [comment]
@cuonglm this does work as expected.  I think that issue linked is mostly around istio.  

FYI, testing this against httpbin will _not_ work.  Apparently httpbin.org strips XFF 🙄 .  When I use https://requestbin.com/, I can see the XFF proxied and appended correctly. 👍

**Comment by cuonglm** [comment]
> @cuonglm this does work as expected. I think that issue linked is mostly around istio.
> 
> FYI, testing this against httpbin will _not_ work. Apparently httpbin.org strips XFF 🙄 . When I use https://requestbin.com/, I can see the XFF proxied and appended correctly. 👍

Thanks FYI, TIL requestbin.com 👍

**Comment by cuonglm** [comment]
@travisgroth oh, found that adding `?show_env=true` also makes httpbin.org show the `X-Forwarded-For`.

**Pull request merged**
