### PR TITLE
proxy: forward_auth honour uri query string when checking policy

### PR DESCRIPTION
**Pull request by whs**
## Summary
Currently forward proxy check the policy for the FORWARD_AUTH_HOST/validate endpoint. This PR changes it to the endpoint given by uri query string, allowing per-endpoint policy like non-forward auth setup.

**Checklist**:
- [ ] updated docs
- [x] updated unit tests
- [x] updated UPGRADING.md
- [x] ready for review

### CODE REVIEW

**Comment by desimone** [comment]
I'm still working on this. Thanks for bearing with me @whs ; I've got some related changes that may conflict.

**Comment by desimone** [comment]
@whs I believe these changes will largely be captured (and superseded) by #1482 . Thoughts?

**Comment by whs** [comment]
Reading the PR description that sounds like what I'm trying to do here. I guess we can close and if it didn't work I might open another PR

**Comment by desimone** [comment]
Thank you @whs !

**Pull request closed without merging**
